### PR TITLE
Remove warning message from about

### PR DESCRIPTION
**Pull request by RobNicholsGDS**
This removed the warning text from the about and index pages.

### CODE REVIEW

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
That removes it from the about page but not the index page.

**Comment by RobNicholsGDS** [comment]
@AlasdairGray I think then update remove the warning from the index page too.

**Comment by RobNicholsGDS** [comment]
I think there may be a bug in my code - just testing

**Review by AlasdairGray — APPROVED** [review]
Changes in both locations have now been made and the warning has been removed from the site.

**Pull request merged**
